language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

script:
  - make test
  - nosetests --with-coverage --cover-package pyrem

after_success:
  - coveralls

branches:
  only:
    - master
